val = int(input('Type value: '))
firstV, val = divmod(val, 1000)
secondV, val = divmod(val, 100)
thirdV, val = divmod(val, 10)
fourthV, val = divmod(val, 1)
print(firstV)
print(secondV)
print(thirdV)
print(fourthV)
